common/models/Gallery.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "gallery".
 *
 * @property integer $id
 * @property string $picture_name
 * @property integer $type
 * @property integer $poi_id
 * @property integer $p_id
 *
 * @property PlacesOfInterest $poi
 * @property Properties $p
 */
class Gallery extends \yii\db\ActiveRecord
{
    const GALLERY_TYPE_POI = 0;
    const GALLERY_TYPE_P   = 1;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'picture_name', 'type'], 'required'],
            [['id', 'type', 'poi_id', 'p_id'], 'integer'],
            [['picture_name'], 'string', 'max' => 256],
            [['poi_id'], 'exist', 'skipOnError' => true, 'targetClass' => PlacesOfInterest::className(), 'targetAttribute' => ['poi_id' => 'id']],
            [['p_id'], 'exist', 'skipOnError' => true, 'targetClass' => Properties::className(), 'targetAttribute' => ['p_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'picture_name' => Yii::t('app', 'Picture'),
            'type' => Yii::t('app', 'Type'),
            'poi_id' => Yii::t('app', 'Poi ID'),
            'p_id' => Yii::t('app', 'P ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPoi()
    {
        return $this->hasOne(PlacesOfInterest::className(), ['id' => 'poi_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getP()
    {
        return $this->hasOne(Properties::className(), ['id' => 'p_id']);
    }
}

backend/controllers/GalleryController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Gallery;
use common\models\GallerySearch;
use backend\components\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Json;
use yii\helpers\FileHelper;
use common\models\PlacesOfInterest;

/**
 * GalleryController implements the CRUD actions for Gallery model.
 */
class GalleryController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Gallery models.
     * @return mixed
     */
    public function actionIndex($id=null, $type=null)
    {
        // $searchModel = new GallerySearch();
        // $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        // return $this->render('index', [
        //     'searchModel' => $searchModel,
        //     'dataProvider' => $dataProvider,
        // ]);

        $model = $this->getModel($id, $type);
        $gallery = null;
        if(!empty($model))
        {
            $gallery_type_id = "";
            switch($type)
            {
                case Gallery::GALLERY_TYPE_POI:
                    $gallery_type_id = "poi_id";
                    break;
                default:
                    return $this->redirect(['/']);
                    break;
            }
            $searchModel = new GallerySearch;
            $queryParams= Yii::$app->request->getQueryParams();
            $queryParams['Gallery']['type'] = $type;
            $queryParams['Gallery'][$gallery_type_id] = $id;
            $gallery = $searchModel->search($queryParams);
            // ->orderBy('id')
            // ->all();
        }
        // echo "<pre>";
        // print_r($gallery);
        // exit();
        return $this->render('gallery', [
            'model' => $model,
            'gallery' => $gallery,
            'id' => $id,
            'type' => $type,
        ]);
    }

    /**
     * Displays a single Gallery model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Gallery model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Gallery();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Gallery model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Gallery model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {

        $this->findModel($id)->delete();

        // $request = Yii::$app->request;
        // $id = $request->get('id');
        // $id = $request->get('id');
        //return $this->redirect(['index']);
    }

    /**
     * Finds the Gallery model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Gallery the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Gallery::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionImageUpload($id, $type)
    {
        $model = $this->getModel($id, $type);

        $imageFile = UploadedFile::getInstance($model, 'picture_name');
        $directory = realpath(dirname(__FILE__).'../../../').'/uploads/gallery/';
        if (!is_dir($directory)) {
            mkdir($directory);
        }
        if ($imageFile) {
            $uid = uniqid(time(), true);
            $fileName = $uid . '.' . $imageFile->extension;
            $filePath = $directory . $fileName;
            if ($imageFile->saveAs($filePath)) {
                $model->picture_name = $fileName;
                $model->save(false);
                $path = \Yii::getAlias('@web') . "/../uploads/gallery/".$fileName;
                return Json::encode([
                    'files' => [[
                        'name' => $fileName,
                        'size' => $imageFile->size,
                        "url" => $path,
                        "thumbnailUrl" => $path,
                        "deleteUrl" => 'image-delete?name=' . $fileName,
                        "deleteType" => "POST"
                    ]]
                ]);
            }
        }
        return '';
    }

    public function actionImageDelete($name)
    {
        $directory = realpath(dirname(__FILE__).'../../../').'/uploads/gallery/';
        if (is_file($directory . DIRECTORY_SEPARATOR . $name)) {
            unlink($directory . DIRECTORY_SEPARATOR . $name);
        }
        $files = FileHelper::findFiles($directory);
        $output = [];
        foreach ($files as $file){
            $path = \Yii::getAlias('@web') . "/../uploads/gallery/".$file;
            $output['files'][] = [
                'name' => basename($file),
                'size' => filesize($file),
                "url" => $path,
                "thumbnailUrl" => $path,
                "deleteUrl" => 'image-delete?name=' . basename($file),
                "deleteType" => "POST"
            ];
        }
        return Json::encode($output);
    }

    private function getModel($id, $type)
    {
        $model = new Gallery();

        if(!isset($id) || !isset($type))
        {
            return $this->redirect(['/']);
        }

        switch($type)
        {
            case Gallery::GALLERY_TYPE_POI:
                if(empty(PlacesOfInterest::findOne(['id' => $id])))
                {
                    return $this->redirect(['/']);
                    exit();
                }
                else
                {
                    $model->poi_id = $id;
                    $model->type = Gallery::GALLERY_TYPE_POI;
                }
                break;
            default:
                return $this->redirect(['/']);
                exit();
                break;
        }

        return $model;
    }

}

backend/views/gallery/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Gallery */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput() ?>

    <?= $form->field($model, 'picture_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type')->textInput() ?>

    <?= $form->field($model, 'poi_id')->textInput() ?>

    <?= $form->field($model, 'p_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/gallery/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\GallerySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gallery-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'picture_name') ?>

    <?= $form->field($model, 'type') ?>

    <?= $form->field($model, 'poi_id') ?>

    <?= $form->field($model, 'p_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/gallery/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Gallery */

$this->title = Yii::t('app', 'Create Gallery');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Galleries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/gallery/gallery.php
    <?php
    use yii\helpers\Html;
    use yii\grid\GridView;
    use yii\widgets\Pjax;
    use yii\widgets\ActiveForm;
    use dosamigos\fileupload\FileUploadUI;

    $this->title = Yii::t('app', 'Gallery');
    $this->params['breadcrumbs'][] = $this->title;

    $this->registerJs("

$(document).on('ready pjax:success', function () {
  $('.ajaxDelete').on('click', function (e) {
    e.preventDefault();
    var deleteUrl     = $(this).attr('delete-url');
    var pjaxContainer = $(this).attr('pjax-container');
    var result = confirm('Are you sure you want to delete this item?');
            
              if (result) {
                $.ajax({
                  url:   deleteUrl,
                  type:  'post',
                  error: function (xhr, status, error) {
                    alert('There was an error with your request.' 
                          + xhr.responseText);
                  }
                }).done(function (data) {
                  $.pjax.reload({container: '#' + $.trim(pjaxContainer)});
                });
              }
  });
});

");

    ?>
    <style type="text/css">
        .preview img{
            max-width:100px !important;
        }
    </style>

    <div class="row">
        <div class="col-md-12">
            <div class="portlet box red">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-picture-o"></i>Gallery
                    </div>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#portlet_tab_1" data-toggle="tab"> Gallery </a>
                            </li>
                            <li>
                                <a href="#portlet_tab_2" data-toggle="tab"> Upload Images </a>
                            </li>
                        </ul>
                </div>
                <div class="portlet-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="portlet_tab_1">
                            <?php Pjax::begin([
                                'id' => 'pjax-list',
                            ]); ?>    
                            <?= GridView::widget([
                                    'dataProvider' => $gallery,
                                    'columns' => [
                                        ['class' => 'yii\grid\SerialColumn'],
                                        [
                                            'attribute' => 'picture_name',
                                            'format' => 'raw',
                                            'filter' => 'none',
                                            'value' => function($data){
                                                return Html::img(\Yii::getAlias('@web') . "/../uploads/gallery/".$data['picture_name'],
                                                    ['width' => '150px', 'max-height'=>'150px']);
                                            },
                                        ],
                                        [
                                            'class' => 'yii\grid\ActionColumn',
                                            'contentOptions' =>['style' => 'width:10%'],
                                            'template' => '{view} {delete}',
                                            'buttons' => [
                                                'delete' => function ($url, $model) {
                                                    return (Html::a(
                                                            '<span class="glyphicon glyphicon-trash"></span>',
                                                            false,
                                                            [
                                                                'class'          => 'ajaxDelete',
                                                                'delete-url'     => $url,
                                                                'pjax-container' => 'pjax-list',
                                                                'title'          => Yii::t('app', 'Delete')
                                                            ]
                                                        ));
                                                }
                                            ],
                                        ],
                                    ],
                                ]); ?>
                            <?php Pjax::end(); ?>
                        </div>
                        <div class="tab-pane" id="portlet_tab_2">
                                <?php $form = ActiveForm::begin(); ?>
                                <?= FileUploadUI::widget([
                                    'model' => $model,
                                    'attribute' => 'picture_name',
                                    'url' => ['gallery/image-upload', 'id' => $id, 'type' => $type],

                                    'fieldOptions' => [
                                    'accept' => 'image/*'
                                    ],
                                    'clientOptions' => [
                                    'maxFileSize' => 2000000
                                    ],
                        // ...
                                    'clientEvents' => [
                                    'fileuploaddone' => 'function(e, data) {
                                        console.log(e);
                                        console.log(data);
                                    }',
                                    'fileuploadfail' => 'function(e, data) {
                                        console.log(e);
                                        console.log(data);
                                    }',
                                    ],
                                    ]);
                                    ?>
                                    <?php ActiveForm::end(); ?>    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

                      

backend/views/gallery/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\models\GallerySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Galleries');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Gallery'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'picture_name',
            'type',
            'poi_id',
            'p_id',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

backend/views/gallery/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Gallery */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Gallery',
]) . $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Galleries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="gallery-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/gallery/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Gallery */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Galleries'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="gallery-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'picture_name',
            'type',
            'poi_id',
            'p_id',
        ],
    ]) ?>

</div>