backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use backend\components\BaseController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\LoginForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;
use backend\models\InitialResetPasswordForm;
use common\models\User;
use common\models\UserProfile;
use common\models\Countries;
use common\models\Destinations;
use common\models\BookingsItems;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'request-password-reset', 'reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'migrate', 'first-login-reset', 'change-password','first-row-data','second-row-data','third-row-data','fourth-row-data'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    // public function actions()
    // {
    //     return [
    //         'error' => [
    //             'class' => 'yii\web\ErrorAction',
    //         ],
    //     ];
    // }

    public function actionIndex()
    {
        $this->view->params['title'] = 'Dashboard';
        $this->view->params['subTitle'] = '  Welcome!';

        // get analytics for widgets
        $reservations = BookingsItems::find()->where(['temp_flag' => 0,'deleted_at' => 0])->count();
        $reservations24hours = BookingsItems::find()
                                            ->where(['temp_flag' => 0,'deleted_at' => 0])
                                            ->andWhere(['>=','created_at', strtotime(date('Y-m-d 00:00:00'))])
                                            ->andWhere(['<=','created_at', strtotime(date('Y-m-d 24:00:00'))])
                                            ->count();
        $users = User::find()->count();
        $providers = Destinations::find()->count();

        return $this->render('index',[
            'reservations' => $reservations,
            'reservations24hours' => $reservations24hours,
            'users' => $users,
            'providers' => $providers,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = 'login';

        if (!Yii::$app->user->isGuest) {
            //logout a user if currently one is active
            // if(isset($_GET['ulg'])){
            //     Yii::$app->user->logout();
            // }
            Yii::$app->user->logout();
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

        /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = 'login';

        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = 'login';

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    /**
     * Reset login on first login
     * @return 
     */
    public function actionFirstLoginReset (){
        $this->layout = 'login';

        try {
            $model = new InitialResetPasswordForm(Yii::$app->user->identity->id);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);



    }

    /**
     * migrate DB
     * @return view 
     */
    public function actionMigrate()
    {
        //default console commands outputs to STDOUT so this needs to be declared for wep app
        if (!defined('STDOUT')) {
            define('STDOUT', fopen('stdout', 'w'));
        }

        //migration command begin
        $migration = new \yii\console\controllers\MigrateController('migrate', Yii::$app);
        $migration->runAction('up', ['migrationPath' => '@console/migrations/', 'interactive' => false]);
        //migration command end

        /**
         * open the STDOUT output file for reading
         * @var $message collects the resulting messages of the migrate command to be displayed in a view
         */
        $handle = fopen('stdout', 'r');
        $message = '';
        while (($buffer = fgets($handle, 4096)) !== false) {
            $message.=$buffer . "<br>";
        }
        fclose($handle);

        return $this->render('migrate', ['message' => $message]);
    }

    /**
     * Change password.
     */
    public function actionChangePassword()
    {
        //$this->layout = 'login';

        try {
            $model = new InitialResetPasswordForm(Yii::$app->user->identity->id);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('changePassword', [
            'model' => $model,
        ]);
    }

    public function actionFirstRowData()
    {
        $current_reservations = BookingsItems::find()->where(['temp_flag' => 0,'deleted_at' => 0])
                                                     ->andWhere(['arrival_date' => date('Y-m-d')])
                                                     ->andWhere(['>','departure_date',date('Y-m-d') ])
                                                     ->count();
        $future_reservations = BookingsItems::find()->where(['temp_flag' => 0,'deleted_at' => 0])
                                                     ->andWhere(['>','arrival_date' ,date('Y-m-d')])
                                                     ->count();
        $completed_reservations = BookingsItems::find()->where(['temp_flag' => 0,'deleted_at' => 0])
                                                     ->andWhere(['<=','departure_date' , date('Y-m-d')])
                                                     ->count();
        $canceled_reservations = BookingsItems::find()->where(['temp_flag' => 0,'deleted_at' => 0])
                                                     ->andWhere(['status_id' => 3])
                                                     ->count();
        $data = array();
        $data['current_reservations'] = $current_reservations;
        $data['future_reservations'] = $future_reservations;
        $data['completed_reservations'] = $completed_reservations;
        $data['canceled_reservations'] = $canceled_reservations;
        
        echo json_encode($data);
    }

    public function actionSecondRowData()
    {
        $time_last24_hrs =  strtotime('-24 hours', time());

        $reservations_created_last_24 = BookingsItems::find()
                                            ->where(['temp_flag' => 0,'deleted_at' => 0])
                                            ->andWhere(['>=','created_at', $time_last24_hrs ])
                                            ->andWhere(['<=','created_at', time() ])
                                            ->count();
        $reservations_canceled_last_24 = BookingsItems::find()
                                            ->where(['temp_flag' => 0,'deleted_at' => 0])
                                            ->andWhere(['status_id' => 3])
                                            ->andWhere(['>=','created_at', $time_last24_hrs ])
                                            ->andWhere(['<=','created_at', time() ])
                                            ->count();
        $deleted_reservatrions = BookingsItems::find()
                                            ->where(['temp_flag' => 0])

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\States;
use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\InitialResetPasswordForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\components\BaseController;

/**
 * Site controller
 */
class SiteController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'change-password'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'change-password'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            // 'error' => [
            //     'class' => 'yii\web\ErrorAction',
            // ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $states = States::find()->where([
            'country_id' => 100,
            'on_main' => 1
        ])
        ->orderBy('order')
        ->all();

        return $this->render('index', [
            'states' => $states,
        ]);
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            //echo Yii::$app->user->identity->id; exit;
            if(Yii::$app->user->identity->type == \common\models\User::USER_TYPE_PMANAGER)
            {
                return $this->redirect(['//provider-admin']);
            }
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {

            if(Yii::$app->user->identity->type == \common\models\User::USER_TYPE_PMANAGER)
            {
                return $this->redirect(['/provider-admin']);
            }
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Reset login on first login
     * @return 
     */
    public function actionFirstLoginReset (){

        try {
            $model = new InitialResetPasswordForm(Yii::$app->user->identity->id);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * Change Password
     */
    public function actionChangePassword(){

        $this->layout = 'login';

        try {
            $model = new InitialResetPasswordForm(Yii::$app->user->identity->id);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }
        return $this->render('changePassword', [
            'model' => $model,
        ]);
    }

    /**
     * error
     */
    public function actionError()
    {
        if(Yii::$app->user->isGuest)
        {
            $this->layout = 'error';
        }
        $exception = Yii::$app->errorHandler->exception;
        if ($exception !== null) {
            return $this->render('error', ['exception' => $exception]);
        }
    }
}

backend/views/site/_login_footer.php
<?php
	// login footer
?>
            <div class="login-footer">
                <div class="row bs-reset">
                    <div class="col-xs-5 bs-reset">
                        <ul class="login-social">
                            <li>
                                <a href="javascript:;">
                                    <i class="icon-social-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="icon-social-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <i class="icon-social-dribbble"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-xs-7 bs-reset">
                        <div class="login-copyright text-right">
                            <p>Copyright &copy; OnlyIceland | <?= Date('Y') ?></p>
                        </div>
                    </div>
                </div>
            </div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $exception->getName() . " (" . $exception->statusCode . ")";
// echo "<pre>";
// print_r($exception);
// exit();
?>
<div class="site-error">

    <div class="page-content">
        
        <div class="row">
            <div class="col-md-12 page-500">
                <div class=" number font-red"> <?= $exception->statusCode ?> </div>
                <div class=" details">
                    <h3>Oops! Something went wrong.</h3>
                    <p>Unable to resolve the request. We can not find the page you're looking for. 
                        <br/> </p>
                    <p>
                        <a href="<?= Url::to(['site/index']) ?>" class="btn red btn-outline"> Return home </a>
                        <br> </p>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Url;
$this->title = 'Dashboard';
?>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 blue">
            <div class="visual">
                <i class="fa fa-bar-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="cu_r" data-value="<?= $reservations; ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Current Reservations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 blue-madison">
            <div class="visual">
                <i class="fa fa-bar-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="fu_r" data-value="<?= $reservations; ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Future Reservations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 blue-steel">
            <div class="visual">
                <i class="fa fa-bar-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="co_r" data-value="<?= $reservations; ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Completed Reservations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 blue-soft">
            <div class="visual">
                <i class="fa fa-bar-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="ca_r" data-value="<?= $reservations; ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Cancelled Reservations </div>
            </div>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 red">
            <div class="visual">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="r_cr_24" data-value="<?= $reservations24hours; ?>" data-counter="counterup"></span> </div>
                <div class="desc"> Reservations Created last 24 hours </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 red-mint">
            <div class="visual">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="r_ca_24" data-value="<?= $reservations24hours; ?>" data-counter="counterup"></span> </div>
                <div class="desc"> Reservations Cancelled last 24 hours </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 red-soft">
            <div class="visual">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="r_de" data-value="<?= $reservations24hours; ?>" data-counter="counterup"></span> </div>
                <div class="desc"> Deleted Reservations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 red-intense">
            <div class="visual">
                <i class="fa fa-line-chart"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="r_de_24" data-value="<?= $reservations24hours; ?>" data-counter="counterup"></span> </div>
                <div class="desc"> Reservations Deleted last 24 hours </div>
            </div>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 green">
            <div class="visual">
                <i class="fa fa-users"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_us" data-value="<?= $users ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Total Registered Users </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 green-soft">
            <div class="visual">
                <i class="fa fa-users"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_us_24" data-value="<?= $users ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> New Registered Users last 24 hours </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 green-dark">
            <div class="visual">
                <i class="fa fa-users"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="mru" data-value="<?= $users ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Country With Most Registered Users </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 green-steel">
            <div class="visual">
                <i class="fa fa-users"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="mru_24" data-value="<?= $users ?>" data-counter="counterup"></span>
                </div>
                <div class="desc"> Country With Most Registered Users Last 24 Hours </div>
            </div>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 purple">
            <div class="visual">
                <i class="fa fa-building"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_de" data-value="<?= $providers ?>" data-counter="counterup"></span> 
                </div>
                <div class="desc"> Total Destinations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 purple-seance">
            <div class="visual">
                <i class="fa fa-building"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_acc" data-value="<?= $providers ?>" data-counter="counterup"></span> 
                </div>
                <div class="desc"> Total Accommodations </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 purple-studio">
            <div class="visual">
                <i class="fa fa-building"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_re" data-value="<?= $providers ?>" data-counter="counterup"></span> 
                </div>
                <div class="desc"> Total Restaurants </div>
            </div>
        </a>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
        <a href="#" class="dashboard-stat dashboard-stat-v2 purple-medium">
            <div class="visual">
                <i class="fa fa-building"></i>
            </div>
            <div class="details">
                <div class="number">
                    <span id="t_si" data-value="<?= $providers ?>" data-counter="counterup"></span> 
                </div>
                <div class="desc"> Total Sights </div>
            </div>
        </a>
    </div>
</div>


<?php
$first_rowUrl = Url::to(['/site/first-row-data']);
$second_rowUrl = Url::to(['/site/second-row-data']);
$third_rowUrl = Url::to(['/site/third-row-data']);
$fourth_rowUrl = Url::to(['/site/fourth-row-data']);
$this->registerJs("

    $(document).ready(function(){
        $.ajax(
                {
                    type: 'GET',
                    url: '$first_rowUrl',
                    success: function(result)
                    {
                        data = jQuery.parseJSON( result );
                        console.log(data);
                        $('#cu_r').html(data.current_reservations);
                        $('#fu_r').html(data.future_reservations);
                        $('#co_r').html(data.completed_reservations);
                        $('#ca_r').html(data.canceled_reservations);
                    },
                });
        $.ajax(
                {
                    type: 'GET',
                    url: '$second_rowUrl',
                    success: function(result)
                    {
                        data = jQuery.parseJSON( result );
                        console.log(data);
                        $('#r_de').html(data.deleted_reservatrions);
                        $('#r_de_24').html(data.deleted_reservatrionsr_last_24);
                        $('#r_ca_24').html(data.reservations_canceled_last_24);
                        $('#r_cr_24').html(data.reservations_created_last_24);
                    },
                });
        $.ajax(
                {
                    type: 'GET',
                    url: '$third_rowUrl',
                    success: function(result)
                    {
                        data = jQuery.parseJSON( result );
                        console.log(data);
                        $('#t_us').html(data.total_users);
                        $('#t_us_24').html(data.total_users_24);
                        if(data.country_mru == null)
                        {
                            $('#mru').html('0');
                        }
                        else
                        {
                            $('#mru').html(data.country_mru+' '+data.max_count_mru);
                        }
                        if(data.country_mru_24 == null)
                        {
                            $('#mru_24').html('0');
                        }
                        else
                        {
                            $('#mru_24').html(data.country_mru_24+' '+data.max_count_mru_24);
                        }
                        
                    },
                });

        $.ajax(
                {
                    type: 'GET',
                    url: '$fourth_rowUrl',
                    success: function(result)
                    {
                        data = jQuery.parseJSON( result );
                        console.log(data);
                        $('#t_de').html(data.total_destinations);
                        $('#t_acc').html(data.total_accomodations);
                        $('#t_re').html(data.total_resturants);
                        $('#t_si').html(data.total_sights);
                    },
                });

    });

        


");


?>