common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use common\models\UserProfile;
use common\models\Properties;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $type
 * @property integer $status
 * @property integer $first_login_reset_flag
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 */
class User extends ActiveRecord implements IdentityInterface
{
    public $server_phone='';
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    const USER_TYPE_ADMIN = 0;
    const USER_TYPE_PMANAGER = 1;
    const USER_TYPE_USER = 2;
    const USER_TYPE_STAFF = 3;
    const USER_TYPE_OWNER = 4;

    const INITIAL_PASSWORD_RESET_PENDING = 0;
    const INITIAL_PASSWORD_RESET_COMPLETE = 1;

    public $password;
    public $current_password;
    public $new_password;

    const SCENARIO_UPDATE = 'update';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // signup rules
            //['username', 'filter', 'filter' => 'trim'],
            ['username', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 2, 'max' => 255],
            //['username', 'match', 'pattern' => '/^[a-z]\w*$/i', 'message' => 'username should start with a letter and contain only word characters'],
            ['email', 'filter', 'filter' => 'trim'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'targetClass' => '\common\models\User', 'message' => 'This email address has already been taken.'],
            ['password', 'string', 'min' => 6],

            //default rules
            [['username', 'email', 'status', 'type'], 'required'],
            [['status', 'created_at', 'updated_at'], 'integer'],
            [['username', 'password_hash', 'password_reset_token', 'email','server_phone'], 'string', 'max' => 255],
            [['auth_key'], 'string', 'max' => 32],
            [['username'], 'unique'],
            [['email'], 'unique'],
            [['password_reset_token'], 'unique'],
            [['first_login_reset_flag'], 'safe'],

            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }


    public function scenarios()
    {
        $scenarios = parent::scenarios();
        // only applies rules for given parameters
        $scenarios[self::SCENARIO_UPDATE] = ['username', 'email', 'status', 'type'];
        //$scenarios[self::SCENARIO_REGISTER] = ['username', 'email', 'password'];
        return $scenarios;
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'username' => Yii::t('app', 'Username'),
            'auth_key' => Yii::t('app', 'Auth Key'),
            'password_hash' => Yii::t('app', 'Password Hash'),
            'password_reset_token' => Yii::t('app', 'Password Reset Token'),
            'email' => Yii::t('app', 'Email'),
            'type' => Yii::t('app', 'Type'),
            'status' => Yii::t('app', 'Status'),
            'first_login_reset_flag' => Yii::t('app', 'Password Reset'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
            'current_password' => Yii::t('app', 'Current Password'),
            'new_password' => Yii::t('app', 'New Password'),
        ];
    }

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by username
     *
     * @param string $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return boolean
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProperties()
    {
        return $this->hasMany(Properties::className(), ['owner_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProfile()
    {
        return $this->hasOne(UserProfile::className(), ['user_id' => 'id']);
    } 
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\UserSearch;
use common\models\UserProfile;
use common\models\UserProfileSearch;
use backend\components\BaseController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\base\Security;
/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'view', 'create', 'update', 'delete'],
                'rules' => [
                    // [
                    //     'actions' => ['signup'],
                    //     'allow' => true,
                    //     'roles' => ['?'],
                    // ],
                    [
                        'actions' => ['index', 'view', 'create', 'update', 'force-reset' ,'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $params = Yii::$app->request->queryParams;

        $session = Yii::$app->session;
        $session->open();

        if(!empty($params))
        {
            if(isset($params['UserSearch']) && !$this->isArrayEmpty($params['UserSearch']) && !isset($params['page']))
            {
                $params['page'] = 1;
            }
            $session[Yii::$app->controller->id.'-grid'] = json_encode($params);
        }
        else if(isset($session[Yii::$app->controller->id.'-grid']) && !empty($session[Yii::$app->controller->id.'-grid']))
        {
            $params = json_decode($session[Yii::$app->controller->id.'-grid'], true);           
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $user_model = new User();
        $profile_model = new UserProfile();
        //$model->scenario = User::SCENARIO_CREATE;
        $post = Yii::$app->request->post();

        if ($user_model->load($post)){

            $password = Yii::$app->security->generateRandomString(12);
            $user_model->setPassword($password);
            $user_model->generateAuthKey();

            if($user_model->save()) 
            {
                if ($profile_model->load($post))
                {
                    $profile_model->user_id = $user_model->id;

                    if($profile_model->same_address==1)
                    {

                        $profile_model->business_address = $profile_model->address;
                        $profile_model->business_city_id = $profile_model->city_id;
                        $profile_model->business_state_id = $profile_model->state_id;
                        $profile_model->business_country_id = $profile_model->country_id;
                        $profile_model->business_postal_code = $profile_model->postal_code;
                        $profile_model->telephone_number = $user_model->server_phone;
                    }
                    $profile_model->telephone_number = $_POST['Users']['server_phone'];
                    
                    $profile_model->save();
                }
                //send email here
                Yii::$app->mailer
                ->compose(
                    ['html' => 'userRegister-html', 'text' => 'userRegister-text'],
                    ['user' => $user_model, 'password' => $password]
                )
                ->setFrom([Yii::$app->params['supportEmail'] => Yii::$app->name . ' Troll'])
                ->setTo($user_model->email)
                ->setSubject('Account created for ' . Yii::$app->name)
                ->send();
                return $this->redirect(['index']);
            } 
        } 
        return $this->render('create', [
            'user_model' => $user_model,
            'profile_model' => $profile_model,
        ]);
    }
    //$2y$13$oGXrnJDJUG1kkbRyOLXuiewUHJkohddUQJycejQPpDgm/RPwiW6JS

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        //echo '<pre>';
        //print_r($_POST);
        //exit;
        $user_model = $this->findModel($id);
        
        if(!isset($user_model->profile)){
            $model = new UserProfile;
            $model->user_id = $user_model->id;
            $model->save();
        }
        
        $profile_model = $this->findProfile($id);
        $user_model->scenario = User::SCENARIO_UPDATE;
        $post = Yii::$app->request->post();

         if ($user_model->load($post)){

            if(isset($post['User']['password']) && !empty($post['User']['password']))
                $user_model->setPassword($post['User']['password']);

            if($user_model->save()) {

                if ($profile_model->load($post))
                {
                    if($profile_model->same_address==1)
                    {
                        $profile_model->business_address = $profile_model->address;
                        $profile_model->business_city_id = $profile_model->city_id;
                        $profile_model->business_state_id = $profile_model->state_id;
                        $profile_model->business_country_id = $profile_model->country_id;
                        $profile_model->business_postal_code = $profile_model->postal_code;
                    }
                    $profile_model->telephone_number = $_POST['Users']['server_phone'];

                    $profile_model->save();
                }
                Yii::$app->session->setFlash('success', 'User Profile is updated successfully');
                return $this->redirect(['index']);
            } 
        } 
        return $this->render('update', [
            'user_model' => $user_model,
            'profile_model' => $profile_model,
        ]);
    }

    /**
     * Force a user to update his/her password on next login
     * @param integer $id
     * @return mixed
     */
    public function actionForceReset($id)
    {
        $model = $this->findModel($id);
        $model->first_login_reset_flag = 0;

         if ($model->save()){
            return $this->redirect(['index']);
        } 
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if(intval($id) != 1)
            $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function findProfile($id)
    {
        if (($model = UserProfile::findOne(['user_id' => $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/users/_old_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'auth_key')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_hash')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password_reset_token')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <?= $form->field($model, 'updated_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?php // echo $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = Yii::t('app', 'Create Users');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'user_model' => $user_model,
        'profile_model' => $profile_model,
    ]) ?>

</div>

backend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use common\models\User;
use backend\components\Helpers;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $searchModel common\models\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Users');
$this->params['breadcrumbs'][] = $this->title;

$update_page_url = Url::to(['/users/update']);
?>
<style type="text/css">
    .show-filters{ display: block; }
    .hide-filters{ display: none; }
    tr:hover{
        cursor: pointer;
    }

    .grid-view .filters input, .grid-view .filters select {
        width: 100%;
    }

    .grid-view td {
        white-space: pre-wrap;
    }

</style>
<div class="users-index">

    <p>
        <?= Html::a(Yii::t('app', 'ADD NEW USER'), ['create'], ['class' => 'pull-right btn btn-primary']) ?>
    </p>
    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(['id' => 'user-gridview','timeout' => 10000, 'enablePushState' => false]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'username',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            'email:email',
            //'status',
            [
                'attribute' => 'type',
                'value' => function($data) {
                    return Helpers::userLables($data->type); 
                },
                'format' => 'raw',
                'filter' => Html::dropDownList(
                    'UserSearch[type]', 
                    $searchModel['type'], 
                    [
                        ""=>"",
                        User::USER_TYPE_ADMIN => Helpers::userLables(User::USER_TYPE_ADMIN, true), 
                        User::USER_TYPE_PMANAGER => Helpers::userLables(User::USER_TYPE_PMANAGER, true), 
                        User::USER_TYPE_USER => Helpers::userLables(User::USER_TYPE_USER, true),
                        User::USER_TYPE_OWNER => Helpers::userLables(User::USER_TYPE_OWNER, true),
                    ],
                    ['class'=>'form-control',
                    'id' => 'type_dropdown']),
                'contentOptions' =>['style' => 'width:15%'],
            ],
            [
                'attribute' => 'status',
                'value' => function($data) {
                    return Helpers::statusLables($data->status); 
                },
                'format' => 'raw',
                'filter' => Html::dropDownList(
                    'UserSearch[status]', 
                    $searchModel['status'], 
                    [
                        ""=>"",
                        User::STATUS_ACTIVE => Helpers::statusLables(User::STATUS_ACTIVE, true), 
                        User::STATUS_DELETED => Helpers::statusLables(User::STATUS_DELETED, true), 
                    ],
                    ['class'=>'form-control',
                    'id' => 'status_dropdown']),
                'contentOptions' =>['style' => 'width:15%'],
            ],
            [
                'attribute' => 'first_login_reset_flag',
                'value' => function($data) {
                    return Helpers::presetLables($data->first_login_reset_flag); 
                },
                'format' => 'raw',
                'filter' => Html::dropDownList(
                    'UserSearch[first_login_reset_flag]', 
                    $searchModel['first_login_reset_flag'], 
                    [
                        ""=>"",
                        User::INITIAL_PASSWORD_RESET_PENDING => Helpers::presetLables(User::INITIAL_PASSWORD_RESET_PENDING, true), 
                        User::INITIAL_PASSWORD_RESET_COMPLETE => Helpers::presetLables(User::INITIAL_PASSWORD_RESET_COMPLETE, true), 
                    ],
                    ['class'=>'form-control',
                    'id' => 'reset_dropdown']),
                'contentOptions' =>['style' => 'width:15%'],
            ],
            // 'created_at',
            // 'updated_at',

            [
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' =>['style' => 'width:10%'],
                'template' => '{force_reset} {view} {update} {delete}',
                'buttons' => [
                    'force_reset' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-off"></span>', Url::to(['force-reset', 'id'=>$model->id]), 
                        [
                            'title' => 'Reset Password',
                        ]);
                    }
                ],
                'visibleButtons' => [
                    // hide delete button for administrator who is logged in
                    'delete' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->id == $model->id ? false : true;
                    },
                    'force_reset' => function ($model, $key, $index) {
                        return Yii::$app->user->identity->id == $model->id ? false : true;
                    },
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

<?php
$this->registerJs("
jQuery(document).ready(function() {

    $('#status_dropdown').select2({
        placeholder: \"Select a Status\",
        allowClear: true
    });

    $('#reset_dropdown').select2({
        placeholder: \"Select an Option\",
        allowClear: true
    });

    $('#type_dropdown').select2({
        placeholder: \"Select a Type\",
        allowClear: true
    });

    $('#user-gridview').on('pjax:end', function() {

        $('#status_dropdown').select2({
            placeholder: \"Select a Status\",
            allowClear: true
        });

        $('#reset_dropdown').select2({
            placeholder: \"Select an Option\",
            allowClear: true
        });

        $('#type_dropdown').select2({
            placeholder: \"Select a Type\",
            allowClear: true
        });
        
    });

    $(document).on('pjax:complete', function() {
      $(document).find('.select2-container').hide();
    });

    $(document).on('click','.table-striped tbody tr',function()
    {
        window.location.replace('$update_page_url?id='+$(this).attr('data-key'));
    });

});",View::POS_END);
?>

backend/views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Users',
]) . $user_model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $user_model->id, 'url' => ['view', 'id' => $user_model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'user_model' => $user_model,
        'profile_model' => $profile_model,
    ]) ?>

</div>

backend/views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Users */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'auth_key',
            'password_hash',
            'password_reset_token',
            'email:email',
            'status',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>